[application]
name = "shell"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "ğŸ¶ Fido"

[web.watcher]
watch_path = ["src", "examples", "public"]

[web.resource]
style = [
  "./app.css",
]
script = []

[web.resource.dev]
script = []